### ISSUE TITLE
issue with retrieving time series of instruments

### ISSUE THREAD

**Issue by hoenie-ams** [ahmedmohamedali/eikonapir#4]
![eikonapir_error](https://user-images.githubusercontent.com/25708487/28515489-21772ac6-705e-11e7-8064-3c5aa6814cf4.jpg)

Retrieving time series for .SPX works fine, but the list of instruments (Microsoft, Vodafone, IBM) results in an error.

Rstudio version 1.0.136, R version is 3.3.2.

**Comment by Nygdat** [comment]
I think this is caused because some equites have an extra column COUNT while others not (see example below). You have to explicitly give the field list, like this:

get_timeseries(list("MSFT.O","VOD.L","IBM.N"),list("TIMESTAMP","HIGH","CLOSE","LOW","OPEN","OPEN"),"2005-01-01T15:04:05","2016-01-10T15:04:05","daily")

Here an example of the problem (second Equity has extra column COUNT):

> df = get_timeseries("AMb.CO",list("*"),"2005-01-01T15:04:05","2016-01-10T15:04:05","monthly")
> head(df)
             TIMESTAMP HIGH CLOSE  LOW OPEN VOLUME     NA
1 2005-01-31T00:00:00Z   33  32.5 28.5   33  50532 AMb.CO
2 2005-02-28T00:00:00Z 34.5    32   32   33  20878 AMb.CO
3 2005-03-31T00:00:00Z   35    32   31 31.5  62699 AMb.CO
4 2005-04-30T00:00:00Z 33.5    29   29   32  17900 AMb.CO
5 2005-05-31T00:00:00Z 31.5  31.5   29 29.5  13025 AMb.CO
6 2005-06-30T00:00:00Z 32.5    32   31   32  21834 AMb.CO
> df = get_timeseries("AAK.ST",list("*"),"2005-01-01T15:04:05","2016-01-10T15:04:05","monthly")
> head(df)
             TIMESTAMP  HIGH CLOSE   LOW  OPEN COUNT  VOLUME     NA
1 2005-09-30T00:00:00Z 144.5   143   141 143.5  <NA>   37100 AAK.ST
2 2005-10-31T00:00:00Z   153   152   140 142.5  <NA>  887184 AAK.ST
3 2005-11-30T00:00:00Z   178   177   144   152  <NA>  494770 AAK.ST
4 2005-12-31T00:00:00Z   190   185   173   180  <NA>  831329 AAK.ST
5 2006-01-31T00:00:00Z   194 183.5   177   178  <NA>  835994 AAK.ST
6 2006-02-28T00:00:00Z   201   200 180.5 183.5  <NA> 1074927 AAK.ST
